export const LOGIN = "LOGIN";
export const ENROLL = "ENROLL";

export const SET_TICKETS = "SET_TICKETS";



export const USER_SIGNIN_PROCESS = "USER_SUBMITTING";
export const USER_SIGNIN_SUCCESS = "USER_SUBMIT_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SUBMIT_FAIL";




export const USER_SIGNUP_PROCESS = "USER_SUBMITTING";
export const USER_SIGNUP_SUCCESS = "USER_SUBMIT_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SUBMIT_FAIL";

export const GET_TICKETS_FROM_DB = "GET_TICKETS_FROM_DB";
export const GET_TICKETS_FROM_DB_FAIL = "GET_TICKETS_FROM_DB";
export const GET_TICKETS_FROM_DB_SUCCESS = "GET_TICKETS_FROM_DB";


//export const ENROLL = "ENROLL"; 